name: CI Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v6
        name: Install Pnpm

      - run: pnpm install
      - run: pnpm test
